sudo: required
os:
  - linux
language: java
jdk:
  - oraclejdk8

before_install:
  - chmod +x mvnw
  - chmod +x mvn

install:
- mvn -N io.takari:maven:wrapper -Dmaven=3.2.5
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V